### ISSUE TITLE
build fails with cmake-js backend and napi runtime

### ISSUE THREAD

**Issue by bsrdjan** [prebuild/prebuild#262]
Build with cmake-js fails with napi runtime:

```shell
$ prebuild --backend cmake-js -r napi
/Users/d037732/src/NG-APPS/node-rfc-cmake/node_modules/napi-build-utils/index.js:190
    pkg.binary.napi_versions.forEach(function (napiVersion) {
                             ^

TypeError: pkg.binary.napi_versions.forEach is not a function
    at Object.exports.getNapiBuildVersions (/Users/d037732/src/NG-APPS/node-rfc-cmake/node_modules/napi-build-utils/index.js:190:30)
    at Object.<anonymous> (/Users/d037732/src/NG-APPS/node-rfc-cmake/node_modules/prebuild/rc.js:47:22)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/Users/d037732/src/NG-APPS/node-rfc-cmake/node_modules/prebuild/bin.js:10:10)
```

**Comment by vweevers** [comment]
What is your expectation? In its current form, `--all` is meant to target all node versions, which makes less sense for N-API because a single N-API prebuilt binary is supposed to work against all node versions.

**Comment by vweevers** [comment]
Correction: `--all` with `--napi` means target all N-API versions.

So you'll need to add the necessary metadata to `package.json` as described here: https://github.com/prebuild/prebuild#n-api-considerations

**Comment by vweevers** [comment]
@bsrdjan I missed your edit (the issue is no longer about `--all`), but the answer is the same :)

**Comment by bsrdjan** [comment]
Thank you. My napi_versions in binary were not an arrray:

```shell
  "binary": {
    "napi_versions": 3,
```

Array fixed it:

```shell
  "binary": {
    "napi_versions": [3],
```
