### ISSUE TITLE
Prebuild upload fails on Windows

### ISSUE THREAD

**Issue by jonhue** [prebuild/prebuild#265]
```
$ D:\a\tree-sitter-quik\tree-sitter-quik\node_modules\.bin\prebuild --all -u
prebuild info begin Prebuild version 9.1.1
prebuild info build Preparing to prebuild tree-sitter-quik@0.7.2 for node 5.0.0 on win32-x64 using node-gyp
prebuild http GET https://nodejs.org/dist/v5.0.0/node-v5.0.0-headers.tar.gz
prebuild http 200 https://nodejs.org/dist/v5.0.0/node-v5.0.0-headers.tar.gz
prebuild http GET https://nodejs.org/dist/v5.0.0/SHASUMS256.txt
prebuild http GET https://nodejs.org/dist/v5.0.0/win-x86/node.lib
prebuild http GET https://nodejs.org/dist/v5.0.0/win-x64/node.lib
prebuild http 200 https://nodejs.org/dist/v5.0.0/SHASUMS256.txt
prebuild http 200 https://nodejs.org/dist/v5.0.0/win-x64/node.lib
prebuild http 200 https://nodejs.org/dist/v5.0.0/win-x86/node.lib
prebuild info spawn C:\ProgramData\Chocolatey\bin\python2.EXE
prebuild info spawn args [
prebuild info spawn args   'D:\\a\\tree-sitter-quik\\tree-sitter-quik\\node_modules\\prebuild\\node_modules\\node-gyp\\gyp\\gyp_main.py',
prebuild info spawn args   'binding.gyp',
prebuild info spawn args   '-f',
prebuild info spawn args   'msvs',
prebuild info spawn args   '-G',
prebuild info spawn args   'msvs_version=2015',
prebuild info spawn args   '-I',
prebuild info spawn args   'D:\\a\\tree-sitter-quik\\tree-sitter-quik\\build\\config.gypi',
prebuild info spawn args   '-I',
prebuild info spawn args   'D:\\a\\tree-sitter-quik\\tree-sitter-quik\\node_modules\\prebuild\\node_modules\\node-gyp\\addon.gypi',
prebuild info spawn args   '-I',
prebuild info spawn args   'C:\\Users\\RUNNER~1\\AppData\\Local\\Temp\\prebuild\\node\\5.0.0\\include\\node\\common.gypi',
prebuild info spawn args   '-Dlibrary=shared_library',
prebuild info spawn args   '-Dvisibility=default',
prebuild info spawn args   '-Dnode_root_dir=C:\\Users\\RUNNER~1\\AppData\\Local\\Temp\\prebuild\\node\\5.0.0',
prebuild info spawn args   '-Dnode_gyp_dir=D:\\a\\tree-sitter-quik\\tree-sitter-quik\\node_modules\\prebuild\\node_modules\\node-gyp',
prebuild info spawn args   '-Dnode_lib_file=C:\\Users\\RUNNER~1\\AppData\\Local\\Temp\\prebuild\\node\\5.0.0\\<(target_arch)\\node.lib',
prebuild info spawn args   '-Dmodule_root_dir=D:\\a\\tree-sitter-quik\\tree-sitter-quik',
prebuild info spawn args   '-Dnode_engine=v8',
prebuild info spawn args   '--depth=.',
prebuild info spawn args   '--no-parallel',
prebuild info spawn args   '--generator-output',
prebuild info spawn args   'D:\\a\\tree-sitter-quik\\tree-sitter-quik\\build',
prebuild info spawn args   '-Goutput_dir=.'
prebuild info spawn args ]
prebuild info spawn C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\15.0\Bin\MSBuild.exe
prebuild info spawn args [
prebuild info spawn args   'build/binding.sln',
prebuild info spawn args   '/clp:Verbosity=minimal',
prebuild info spawn args   '/nologo',
prebuild info spawn args   '/p:Configuration=Release;Platform=x64'
prebuild info spawn args ]
events.js:200
      throw er; // Unhandled 'error' event
      ^

Error: spawn C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\15.0\Bin\MSBuild.exe ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)
    at onErrorNT (internal/child_process.js:456:16)
    at processTicksAndRejections (internal/process/task_queues.js:81:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:270:12)
    at onErrorNT (internal/child_process.js:456:16)
    at processTicksAndRejections (internal/process/task_queues.js:81:21) {
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'spawn C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Enterprise\\MSBuild\\15.0\\Bin\\MSBuild.exe',
  path: 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Enterprise\\MSBuild\\15.0\\Bin\\MSBuild.exe',
  spawnargs: [
    'build/binding.sln',
    '/clp:Verbosity=minimal',
    '/nologo',
    '/p:Configuration=Release;Platform=x64'
  ]
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
##[error]Process completed with exit code 1.
```

I'm running this on `windows-latest` on GitHub actions.

**Comment by vweevers** [comment]
Maybe you need something like https://github.com/warrenbuckley/Setup-MSBuild to locate msbuild?

**Comment by vweevers** [comment]
#264 might also help because `node-gyp@5` landed support for VS 2019.

**Comment by jonhue** [comment]
Upgrading to v10 fixed it. Thanks!
