### ISSUE TITLE
Prebuild N-API module using cmake-js, for Electron

### ISSUE THREAD

**Issue by bsrdjan** [prebuild/prebuild#269]
**prebuild version**: 10.0.0
**cmake-js version**: 6.1.0
**cmake version**:  3.17.0-rc1
**node version**: 12.13.0
**electron version**: 8.2.5
**platform**: Windows 10

Hi,

the node-rfc **napi** module, built with **prebuild** and **cmake** ([CMakeLists.txt](https://github.com/SAP/node-rfc/blob/master/CMakeLists.txt)), works fine on Linux, Darwin and Windows. The module works also from Electron, on Linux and Darwin and does not load on in Electron on Windows, showing `A dynamic link library (DLL) initialization routine failed.` error.

Electron [troubleshooting methods](https://www.electronjs.org/docs/tutorial/using-native-node-modules) did not help and I now try to build a napi module for Electron runtime, on Windows. I am not sure if I am doing it correctly because the build works but the module still shows the same error in Electron.

**Standard build**

```shell
PS C:\src\node-rfc> prebuild.cmd --backend cmake-js -r napi --force
prebuild info begin Prebuild version 10.0.0
prebuild info build Preparing to prebuild node-rfc@1.2.0 for napi 3 on win32-x64 using cmake-js
[
  'C:\\Tools\\nvm-node\\node.exe',
  'C:\\src\\node-rfc\\node_modules\\cmake-js\\bin\\cmake-js',
  'rebuild',
  '--arch=x64',
  '--CDnapi_build_version=3'
]
info TOOL Using Visual Studio 16 2019 generator.
info CMD CLEAN
info RUN cmake -E remove_directory "C:\src\node-rfc\build"
info CMD CONFIGURE
info RUN cmake "C:\src\node-rfc" --no-warn-unused-cli -G"Visual Studio 16 2019" -A"x64" 
-DCMAKE_JS_VERSION="6.1.0" -DCMAKE_BUILD_TYPE="Release" 
-DCMAKE_RUNTIME_OUTPUT_DIRECTORY="C:\src\node-rfc\build" 
-DCMAKE_JS_INC="C:\Users\d037732\.cmake-js\node-x64\v12.13.0\include\node;C:\src\node-rfc\node_modules\nan" 
-DCMAKE_JS_SRC="C:/src/node-rfc/node_modules/cmake-js/lib/cpp/win_delay_load_hook.cc" 
-DNODE_RUNTIME="node" -DNODE_RUNTIMEVERSION="12.13.0" -DNODE_ARCH="x64" 
-DCMAKE_JS_LIB="C:\Users\d037732\.cmake-js\node-x64\v12.13.0\win-x64\node.lib" 
-Dnapi_build_version="3" 
-DCMAKE_SHARED_LINKER_FLAGS="/DELAYLOAD:NODE.EXE"
Not searching for unused variables given on the command line.
-- Selecting Windows SDK version 10.0.18362.0 to target Windows 10.0.18363.
-- The C compiler identification is MSVC 19.24.28316.0
-- The CXX compiler identification is MSVC 19.24.28316.0
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/BuildTools/VC/Tools/MSVC/14.24.28314/bin/Hostx64/x64/cl.exe
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/BuildTools/VC/Tools/MSVC/14.24.28314/bin/Hostx64/x64/cl.exe - works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/BuildTools/VC/Tools/MSVC/14.24.28314/bin/Hostx64/x64/cl.exe
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/BuildTools/VC/Tools/MSVC/14.24.28314/bin/Hostx64/x64/cl.exe - works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
SAP NWRFC SDK: 750 Patch Level 6

-- Configuring done
-- Generating done
-- Build files have been written to: C:/src/node-rfc/build
info CMD BUILD
info RUN cmake --build "C:\src\node-rfc\build" --config Release
Microsoft (R) Build Engine version 16.4.0+e901037fe for .NET Framework
PS C:\src\node-rfc> prebuild.cmd --backend cmake-js -r napi --verbose --force
prebuild info begin Prebuild version 10.0.0
prebuild info build Preparing to prebuild node-rfc@1.2.0 for napi 3 on win32-x64 using cmake-js
prebuild verb starting build process cmake-js
[
  'C:\\Tools\\nvm-node\\node.exe',
  'C:\\src\\node-rfc\\node_modules\\cmake-js\\bin\\cmake-js',
  'rebuild',
  '--arch=x64',
  '--CDnapi_build_version=3'
]
info TOOL Using Visual Studio 16 2019 generator.
info CMD CLEAN
info RUN cmake -E remove_directory "C:\src\node-rfc\build"
info CMD CONFIGURE
info RUN cmake "C:\src\node-rfc" --no-warn-unused-cli -G"Visual Studio 16 2019" -A"x64" 
-DCMAKE_JS_VERSION="6.1.0" -DCMAKE_BUILD_TYPE="Release" 
-DCMAKE_RUNTIME_OUTPUT_DIRECTORY="C:\src\node-rfc\build" 
-DCMAKE_JS_INC="C:\Users\d037732\.cmake-js\node-x64\v12.13.0\include\node;C:\src\node-rfc\node_modules\nan" 
-DCMAKE_JS_SRC="C:/src/node-rfc/node_modules/cmake-js/lib/cpp/win_delay_load_hook.cc" 
-DNODE_RUNTIME="node" -DNODE_RUNTIMEVERSION="12.13.0" -DNODE_ARCH="x64"
-DCMAKE_JS_LIB="C:\Users\d037732\.cmake-js\node-x64\v12.13.0\win-x64\node.lib" 
-Dnapi_build_version="3" 
-DCMAKE_SHARED_LINKER_FLAGS="/DELAYLOAD:NODE.EXE"
Not searching for unused variables given on the command line.
-- Selecting Windows SDK version 10.0.18362.0 to target Windows 10.0.18363.
-- The C compiler identification is MSVC 19.24.28316.0
-- The CXX compiler identification is MSVC 19.24.28316.0
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/BuildTools/VC/Tools/MSVC/14.24.28314/bin/Hostx64/x64/cl.exe
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/BuildTools/VC/Tools/MSVC/14.24.28314/bin/Hostx64/x64/cl.exe - works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/BuildTools/VC/Tools/MSVC/14.24.28314/bin/Hostx64/x64/cl.exe
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/BuildTools/VC/Tools/MSVC/14.24.28314/bin/Hostx64/x64/cl.exe - works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
SAP NWRFC SDK: 750 Patch Level 6

-- Configuring done
-- Generating done
info CMD BUILD
info RUN cmake --build "C:\src\node-rfc\build" --config Release
-- Build files have been written to: C:/src/node-rfc/build
Microsoft (R) Build Engine version 16.4.0+e901037fe for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

  Checking Build System
  Building Custom Rule C:/src/node-rfc/CMakeLists.txt
  node_sapnwrfc.cc
  Client.cc
  rfcio.cc
  noderfcsdk.cc
  Throughput.cc
     Creating library C:/src/node-rfc/build/Release/sapnwrfc.lib and object C:/src/node-rfc/build/Release/sapnwrfc.exp
  Generating code
C:\src\node-rfc\src\noderfcsdk.cc(153): warning C4715: 'node_rfc::wrapError': not all control paths return a value [C:\src\node-rfc\build\sapnwrfc.vcxproj]
  Finished generating code
  sapnwrfc.vcxproj -> C:\src\node-rfc\build\Release\sapnwrfc.node
  C:/src/node-rfc/lib/binding/
  Building Custom Rule C:/src/node-rfc/CMakeLists.txt
prebuild verb completed building cmake-js
prebuild info build Packing lib\binding\sapnwrfc.node into prebuilds\node-rfc-v1.2.0-napi-v3-win32-x64.tar.gz
prebuild info build Prebuild written to prebuilds\node-rfc-v1.2.0-napi-v3-win32-x64.tar.gz
```

**napi for Electron**

ends with an error:

```shell
PS C:\src\node-rfc> prebuild.cmd --backend cmake-js -r electron --verbose --force
prebuild info begin Prebuild version 10.0.0
prebuild info build Preparing to prebuild node-rfc@1.2.0 for electron 12.13.0 on win32-x64 using cmake-js
C:\src\node-rfc\node_modules\node-abi\index.js:30
  throw new Error('Could not detect abi for version ' + target + ' and runtime ' + runtime + '.  Updating "node-abi" might help solve this issue if it is a new release of ' + runtime)
  ^

Error: Could not detect abi for version 12.13.0 and runtime electron.  Updating "node-abi" might help solve this issue if it is a new release of electron
    at getAbi (C:\src\node-rfc\node_modules\node-abi\index.js:30:9)
    at prebuild (C:\src\node-rfc\node_modules\prebuild\prebuild.js:27:13)
    at C:\src\node-rfc\node_modules\prebuild\bin.js:51:5
    at invoke (C:\src\node-rfc\node_modules\each-series-async\index.js:32:5)
    at each (C:\src\node-rfc\node_modules\each-series-async\index.js:39:5)
    at Object.<anonymous> (C:\src\node-rfc\node_modules\prebuild\bin.js:50:3)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
```

which I tried to fix by:

```shell
PS C:\src\node-rfc> prebuild.cmd --backend cmake-js -t 8.2.5 -r electron --verbose --force
prebuild info begin Prebuild version 10.0.0
prebuild info build Preparing to prebuild node-rfc@1.2.0 for electron 8.2.5 on win32-x64 using cmake-js
prebuild verb starting build process cmake-js 
[
  'C:\\Tools\\nvm-node\\node.exe',
  'C:\\src\\node-rfc\\node_modules\\cmake-js\\bin\\cmake-js',
  'rebuild',
  '--runtime-version=8.2.5',
  '--arch=x64',
  '--runtime=electron'
]
info TOOL Using Visual Studio 16 2019 generator.
info CMD CLEAN
info RUN cmake -E remove_directory "C:\src\node-rfc\build"
info CMD CONFIGURE
info RUN cmake "C:\src\node-rfc" --no-warn-unused-cli -G"Visual Studio 16 2019" -A"x64"
-DCMAKE_JS_VERSION="6.1.0" -DCMAKE_BUILD_TYPE="Release" 
-DCMAKE_RUNTIME_OUTPUT_DIRECTORY="C:\src\node-rfc\build" 
-DCMAKE_JS_INC="C:\Users\d037732\.cmake-js\electron-x64\v8.2.5\include\node;C:\src\node-rfc\node_modules\nan" 
-DCMAKE_JS_SRC="C:/src/node-rfc/node_modules/cmake-js/lib/cpp/win_delay_load_hook.cc" 
-DNODE_RUNTIME="electron" -DNODE_RUNTIMEVERSION="8.2.5" -DNODE_ARCH="x64" 
-DCMAKE_JS_LIB="C:\Users\d037732\.cmake-js\electron-x64\v8.2.5\x64\node.lib" 
-DCMAKE_SHARED_LINKER_FLAGS="/DELAYLOAD:NODE.EXE"
Not searching for unused variables given on the command line.
-- Selecting Windows SDK version 10.0.18362.0 to target Windows 10.0.18363.
-- The C compiler identification is MSVC 19.24.28316.0
-- The CXX compiler identification is MSVC 19.24.28316.0
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/BuildTools/VC/Tools/MSVC/14.24.28314/bin/HosPS C:\src\node-rfc> prebuild.cmd --backend cmake-js -t 8.2.5 -r electron --verbose --force
prebuild info begin Prebuild version 10.0.0
prebuild info build Preparing to prebuild node-rfc@1.2.0 for electron 8.2.5 on win32-x64 using cmake-js
prebuild verb starting build process cmake-js 
[
  'C:\\Tools\\nvm-node\\node.exe',
  'C:\\src\\node-rfc\\node_modules\\cmake-js\\bin\\cmake-js',
  'rebuild',
  '--runtime-version=8.2.5',
  '--arch=x64',
  '--runtime=electron'
]
info TOOL Using Visual Studio 16 2019 generator.
info CMD CLEAN
info RUN cmake -E remove_directory "C:\src\node-rfc\build"
info CMD CONFIGURE
info RUN cmake "C:\src\node-rfc" --no-warn-unused-cli -G"Visual Studio 16 2019" -A"x64" 
-DCMAKE_JS_VERSION="6.1.0" -DCMAKE_BUILD_TYPE="Release" 
-DCMAKE_RUNTIME_OUTPUT_DIRECTORY="C:\src\node-rfc\build" 
-DCMAKE_JS_INC="C:\Users\d037732\.cmake-js\electron-x64\v8.2.5\include\node;C:\src\node-rfc\node_modules\nan" 
-DCMAKE_JS_SRC="C:/src/node-rfc/node_modules/cmake-js/lib/cpp/win_delay_load_hook.cc" 
-DNODE_RUNTIME="electron" -DNODE_RUNTIMEVERSION="8.2.5" -DNODE_ARCH="x64" 
-DCMAKE_JS_LIB="C:\Users\d037732\.cmake-js\electron-x64\v8.2.5\x64\node.lib" 
-DCMAKE_SHARED_LINKER_FLAGS="/DELAYLOAD:NODE.EXE"
Not searching for unused variables given on the command line.
-- Selecting Windows SDK version 10.0.18362.0 to target Windows 10.0.18363.
-- The C compiler identification is MSVC 19.24.28316.0
-- The CXX compiler identification is MSVC 19.24.28316.0
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/BuildTools/VC/Tools/MSVC/14.24.28314/bin/Hostx64/x64/cl.exe
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/BuildTools/VC/Tools/MSVC/14.24.28314/bin/Hostx64/x64/cl.exe - works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/BuildTools/VC/Tools/MSVC/14.24.28314/bin/Hostx64/x64/cl.exe
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/BuildTools/VC/Tools/MSVC/14.24.28314/bin/Hostx64/x64/cl.exe - works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
SAP NWRFC SDK: 750 Patch Level 6

-- Configuring done
-- Generating done
-- Build files have been written to: C:/src/node-rfc/build
info CMD BUILD
info RUN cmake --build "C:\src\node-rfc\build" --config Release
Microsoft (R) Build Engine version 16.4.0+e901037fe for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

  Checking Build System
  Building Custom Rule C:/src/node-rfc/CMakeLists.txt
  node_sapnwrfc.cc
  Client.cc
  rfcio.cc
  noderfcsdk.cc
  Throughput.cc
     Creating library C:/src/node-rfc/build/Release/sapnwrfc.lib and object C:/src/node-rfc/build/Release/sapnwrfc.exp
  Generating code
C:\src\node-rfc\src\noderfcsdk.cc(153): warning C4715: 'node_rfc::wrapError': not all control paths return a value [C:\src\node-rfc\build\sapnwrfc.vcxproj]
  Finished generating code
  sapnwrfc.vcxproj -> C:\src\node-rfc\build\Release\sapnwrfc.node
  C:/src/node-rfc/lib/binding/
  Building Custom Rule C:/src/node-rfc/CMakeLists.txt
prebuild verb completed building cmake-js
prebuild info build Packing lib\binding\sapnwrfc.node into prebuilds\node-rfc-v1.2.0-electron-v76-win32-x64.tar.gz
prebuild info build Prebuild written to prebuilds\node-rfc-v1.2.0-electron-v76-win32-x64.tar.gz
PS C:\src\node-rfc> 
```

This build shows the same error when the module loaded in Electron and I am not sure if my build command is correct?

Any hint what could be the problem here or a pointer to working napi/cmake/prebuild/Electron example would be of a great help.

**Comment by bung87** [comment]
same here in my repo https://github.com/bung87/awtk-node-gen  
I tried two days ,  module install via prebuild-install  
I also add  postinstall script electron-builder  install-app-deps  
I built multiple runtime target to electron 11.2.1,napi 6, node 12.18.3 that's all exactly match my app electron version  throught process.versions
none of them works on windows when starting electron  
all of them works on mac and windows when running on node , mac also work on electron.

**Comment by bung87** [comment]
I solve this by 
`set_target_properties(${PROJECT_NAME} PROPERTIES LINK_FLAGS "${CMAKE_SHARED_LINKER_FLAGS}" ) `  
I use cmake-js  CMAKE_SHARED_LINKER_FLAGS  equals `/DELAYLOAD:node.exe`  
I install my native module runtime to `electron` and works fine on windows now.

`target_link_libraries(${PROJECT_NAME} ${CMAKE_JS_LIB} ${OS_LIBS}` while OS_LIBS contains "DelayImp.lib"  

CMAKE_JS_LIB contains `node.lib`  

also follow cmake Include N-API wrappers section 

```
execute_process(COMMAND node -p "require('node-addon-api').include"
        WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}
        OUTPUT_VARIABLE NODE_ADDON_API_DIR
        )
string(REPLACE "\n" "" NODE_ADDON_API_DIR ${NODE_ADDON_API_DIR})
string(REPLACE "\"" "" NODE_ADDON_API_DIR ${NODE_ADDON_API_DIR})
target_include_directories(${PROJECT_NAME} PRIVATE ${NODE_ADDON_API_DIR} )
```

so I think here is 3 key points:
1.  LINK_FLAGS `/DELAYLOAD:node.exe`  
2. link library "DelayImp.lib"  and `node.lib`  
3.  include_directories "require('node-addon-api').include"  

these mentioned in electron's document and cmake-js's readme but they don't provide a full example.

also I'd mention I literally set `add_compile_definitions(NAPI_VERSION=6)`  since electron is combination of napi and node
